### PR TITLE
Added Watch providers to TV and Movie

### PR DESCRIPTION
**Pull request by tobiasge**
Added a method to TV and Movie to load the watch providers list.

### CODE REVIEW

**Review by martinimarcello00 — APPROVED** [review]
I tried and tested the `movie.watch_providers()` method on a project and works very well!

**Comment by meisnate12** [comment]
i added ever method in the api not in this wrapper in my other pull and it hasn't been accepted for months

**Review by BackrndSource — APPROVED** [review]
Looks great!

**Comment by BackrndSource** [comment]
Sorry for the time I took and thank you!
For the update on PyPI need to talk with Anthony

**Pull request merged**
