### PR TITLE
Implemented cache system.

### PR DESCRIPTION
**Pull request by BackrndSource**
Tmdb's api limits to 40 requests every 10 seconds currently. It is a good practice to cache the application responses, to reduce resource consumption and avoid further problems. For example, let's imagine that we implement this API on a website that makes a request to tmdbapi every time a user accesses a page. If a malicious user repeats the same operation 40 times in less than 10 seconds it will cause the website to fall for a few seconds. A simple method would be to store the answers in our database. And update this data periodically. But much simpler would be if we stored the responses of the Api in cache, so as not to overload our database with unnecessary data.

 - Using library functools (python 3+) https://docs.python.org/3/library/functools.html

 - Only method cached is `cached_request(url)`, which calls the function `request.get(url)`. The cache discriminates according to the `url `parameter, if is repeated, it will deliver a cached version of the response.

 - If `cached `param is True in `_call()` method run `cached_request(url)`, else runs `request.get(url)` without caching. At the moment all requests can be cached, but I did it in case you want to add account functions from TmdbApi in the future. In any case by default the cache parameter will be True

 - Constant `REQUEST_CACHE_MAXSIZE `will define the maxsize of the cache, None by default (no limit). The problem is that I cannot use a variable to define the `maxsize `parameter of the `@lru_cache `decorator, then users should adjust this manually. I can't find another solution

 - Another problem to solve is that users should clean the cache periodically if they do not restart their applications. That is why I have added the `cache_clear()` method to TMDb class, which can be called periodically.

 - I can see in /requeriments.txt  that the backport of functools for Python 3.0+ and 2.6+ is already added, `backports.functools-lru-cache==1.5`, but never used. I use Python 3.3+, so I have not tried the backport.

 - In debug mode the information of the cache status is printed on the terminal

### CODE REVIEW

**Comment by AnthonyBloomer** [comment]
Hi @BackrndSource, Nice work! Really cool contribution.

In terms of allowing the user define the maxsize parameter of the `@lru_cache` decorator, the user could specify the cache maxsize by passing that value to the `__init__` method: 

``` python
def __init__(self, max_size=None):
    self._base = 'http://api.themoviedb.org/3'
    self._remaining = 40
    self._reset = None
    self._cached = True
    self.REQUEST_CACHE_MAXSIZE = max_size
```

I noticed that you have added the `cached` variable to the `_call` function. This boolean determines whether to use the cache or not. For whatever reason the user doesn't want to use this awesome feature, then they have no way to set it to False other than going into the module and disabling it there since `_call` is a private function. We could either add a new variable to `__init__` or add a class method to allow the user to set it there. What do you think?

**Comment by BackrndSource** [comment]
I do not understand in depth how python executes the decorators. In the case of the decorator `@lru_cache` we can enter a `maxsize ` attribute, which can be an attribute of the class in which the method is defined, in this case `REQUEST_CACHE_MAXSIZE`. But we can't use `self.REQUEST_CACHE_MAXSIZE` in any case, if not we receive the following error:

```
@lru_cache(maxsize=self.REQUEST_CACHE_MAXSIZE)
NameError: name 'self' is not defined
```

If we do it as you indicate: defining this attribute only in `__init__`, we still receiving the same error:

```
@lru_cache(maxsize=REQUEST_CACHE_MAXSIZE)
NameError: name 'REQUEST_CACHE_MAXSIZE' is not defined
```

However, if we define the attribute outside of `__init__`, we do not get this error. But if we modify the attribute later, in `__init__ ` or another method, the decorator will not appreciate it.

It makes me think that the decorator uses the attribute of the class (`TMDb `in this case) before instantiating / initializing / defining the object. I don't know how I can call this. So for the moment I leave it that way...

**Comment by BackrndSource** [comment]
Merge branch 'master' into patch-2 is for resolve conflicts with your new commit

**Comment by BackrndSource** [comment]
I have added other ways to disable the cache in last commit.

**Comment by BackrndSource** [comment]
In last commit I have left three ways to disable the cache (it will always be enabled by default).

 - The one that was already established (only for tmdbv3api developers), allows to define if a call to the `_call ` method is cached. I have renamed the parameter `cached ` to `call_cached `.

 - Defined as an attribute of the TMDb class. You can disable the cache by instantiating a `TMDb` subclass object. For example:

```
Movie(obj_cached = False)
Movie(True)
Movie() #default is True
```
- Defined as environment variable. It allows to deactivate the cache completely, in all calls regardless of the other configuration. You can set it like other configuration settings:

```
tmdb = TMDb()
tmdb.cache = True #or False
```

**Comment by AnthonyBloomer** [comment]
This feature has been added to v1.5.1 and is now available on PyPI: https://pypi.org/project/tmdbv3api/

**Pull request merged**
